[project]
name = "scy"
version = "0.0.1"
description = "Sequence of Covers with Yosys"

dependencies = [
    "yosys_mau @ git+https://github.com/YosysHQ/mau@main"
]

[project.scripts]
scy = "scy.scy:main"
